# Generated by Django 5.2 on 2026-08-18 11:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_maintenancecomplaint_user_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))]),
        ),
    ]
